import type { Metadata } from 'next';
import '@/styles/reset.css';
import '@/app/globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  auth,
}: Readonly<{
  children: React.ReactNode;
  auth: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        {auth}
        {children}
      </body>
    </html>
  );
}
