import type { Metadata } from 'next';
import '@/styles/reset.css';
import '@/app/globals.css';
import '@/styles/tokens.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

/**
 * Root layout component that renders the top-level HTML document with page content and a modal.
 *
 * @param children - The page content to render inside the document body.
 * @param modal - Modal content that will be rendered after `children` inside the body.
 * @returns The root HTML element containing a body that hosts `children` followed by `modal`.
 */
export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        {children}
        {modal}
      </body>
    </html>
  );
}